import Head from "next/head";
import styles from "../styles/Home.module.css";
import Logo from "../components/atoms/Logo";
import { useEffect, useState } from "react";

export default function Home() {
  const [helloWorld, setHello] = useState("");

  useEffect(() => {
    const getData = async () => {
      try {
        const result = await fetch("/api/hello");
        const data = await result.json();
        setHello(data.name);
      } catch (e) {
        console.error("This is the error", e);
      }
    };

    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>KGB Whisky</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="go:description"
          content="Generated by create next app"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{helloWorld}</h1>
      </main>

      <footer className={styles.footer}>
        Some contact info <Logo height={100} />
      </footer>
    </div>
  );
}
