name: Check and test the project

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    name: project-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install deps
        run: yarn install --immutable --immutable-cache

      - name: Verify all tests
        run: yarn fix